workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - keystore_credentials
      vars:
        APP_ID: "com.example.test_zak_flutter"
        FLUTTER_BUILD_MODE: "release"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        APP_ID: "com.example.test_zak_flutter"
        FLUTTER_BUILD_MODE: "release"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter test
        script: |
          flutter test
      - name: Build iOS IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
